openapi: "3.0.0"
info:
  version: "0.0.3"   
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: https://codeforsapporo.github.io/v1
paths:
  "/pets":
    $ref: "./paths/pets.yml"
  "/pets/{petId}":
    $ref: "./paths/pets.petid.yml"
components:
  schemas:
    $ref: "./schemas/index.yml"
