name: ReleaseWorkflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy-pages:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install, build
        run: |
          npm ci
          npm run build:pages
          ls

  generate-src:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install, generate
        run: |
          npm ci
          npm run generate:axios
      - name: Upload for generate-src
        uses: actions/upload-artifact@v2
        with:
          name: generate-src
          path: ./typescript-axios-src

  npm-publish:
    runs-on: ubuntu-20.04
    needs: generate-src
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Download for generate-src
        uses: actions/download-artifact@v2
        with:
          name: generate-src
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      - run: ls -a /home/runner/work/_temp
      - run: cat /home/runner/work/_temp/.npmrc
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
